function pos = newleg_pos(l1,l2,l3,l4,l5,l6,phi1,phi4)
%NEWLEG_POS
%    POS = NEWLEG_POS(L1,L2,L3,L4,L5,L6,PHI1,PHI4)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-02-09 14:23:00

t2 = cos(phi1);
t3 = cos(phi4);
t4 = sin(phi1);
t5 = sin(phi4);
t6 = l2+l6;
t7 = l2.^2;
t8 = l3.^2;
t13 = 1.0./l2;
t14 = l5./2.0;
t9 = l1.*t2;
t10 = l4.*t3;
t11 = l1.*t4;
t12 = l4.*t5;
t15 = -t8;
t16 = -t9;
t17 = -t12;
t18 = l6.*t9.*t13;
t19 = t11+t17;
t20 = l5+t10+t16;
t21 = t19.^2;
t22 = t20.^2;
t23 = l2.*t19.*2.0;
t25 = l2.*t20.*2.0;
t26 = t7.*t21.*4.0;
t27 = t7.*t22.*4.0;
t28 = t7+t15+t21+t22;
t29 = t28.^2;
t31 = t25+t28;
t30 = -t29;
t32 = 1.0./t31;
t33 = t26+t27+t30;
t34 = sqrt(t33);
t36 = -t32.*(t23-t34);
t37 = atan(t36);
t38 = t37.*2.0;
t39 = cos(t38);
t40 = sin(t38);
t41 = l2.*t39;
t42 = l2.*t40;
t43 = t9+t41;
t44 = t11+t42;
t45 = t6.*t13.*t43;
pos = [sqrt((l6.*t11.*t13-t6.*t13.*t44).^2+(t14+t18-t45).^2);pi./2.0-atan2(-l6.*t11.*t13+t6.*t13.*t44,-t14+t45+l6.*t13.*t16)];
end
